// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/proto/webhook.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookInternal_GetEndpoint_FullMethodName            = "/webhook.v1.WebhookInternal/GetEndpoint"
	WebhookInternal_GetCircuitBreakerState_FullMethodName = "/webhook.v1.WebhookInternal/GetCircuitBreakerState"
)

// WebhookInternalClient is the client API for WebhookInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookInternalClient interface {
	GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error)
	GetCircuitBreakerState(ctx context.Context, in *GetCircuitBreakerStateRequest, opts ...grpc.CallOption) (*GetCircuitBreakerStateResponse, error)
}

type webhookInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookInternalClient(cc grpc.ClientConnInterface) WebhookInternalClient {
	return &webhookInternalClient{cc}
}

func (c *webhookInternalClient) GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEndpointResponse)
	err := c.cc.Invoke(ctx, WebhookInternal_GetEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookInternalClient) GetCircuitBreakerState(ctx context.Context, in *GetCircuitBreakerStateRequest, opts ...grpc.CallOption) (*GetCircuitBreakerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCircuitBreakerStateResponse)
	err := c.cc.Invoke(ctx, WebhookInternal_GetCircuitBreakerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookInternalServer is the server API for WebhookInternal service.
// All implementations must embed UnimplementedWebhookInternalServer
// for forward compatibility.
type WebhookInternalServer interface {
	GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error)
	GetCircuitBreakerState(context.Context, *GetCircuitBreakerStateRequest) (*GetCircuitBreakerStateResponse, error)
	mustEmbedUnimplementedWebhookInternalServer()
}

// UnimplementedWebhookInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookInternalServer struct{}

func (UnimplementedWebhookInternalServer) GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEndpoint not implemented")
}
func (UnimplementedWebhookInternalServer) GetCircuitBreakerState(context.Context, *GetCircuitBreakerStateRequest) (*GetCircuitBreakerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCircuitBreakerState not implemented")
}
func (UnimplementedWebhookInternalServer) mustEmbedUnimplementedWebhookInternalServer() {}
func (UnimplementedWebhookInternalServer) testEmbeddedByValue()                         {}

// UnsafeWebhookInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookInternalServer will
// result in compilation errors.
type UnsafeWebhookInternalServer interface {
	mustEmbedUnimplementedWebhookInternalServer()
}

func RegisterWebhookInternalServer(s grpc.ServiceRegistrar, srv WebhookInternalServer) {
	// If the following call panics, it indicates UnimplementedWebhookInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookInternal_ServiceDesc, srv)
}

func _WebhookInternal_GetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookInternalServer).GetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookInternal_GetEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookInternalServer).GetEndpoint(ctx, req.(*GetEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookInternal_GetCircuitBreakerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCircuitBreakerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookInternalServer).GetCircuitBreakerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookInternal_GetCircuitBreakerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookInternalServer).GetCircuitBreakerState(ctx, req.(*GetCircuitBreakerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookInternal_ServiceDesc is the grpc.ServiceDesc for WebhookInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhook.v1.WebhookInternal",
	HandlerType: (*WebhookInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEndpoint",
			Handler:    _WebhookInternal_GetEndpoint_Handler,
		},
		{
			MethodName: "GetCircuitBreakerState",
			Handler:    _WebhookInternal_GetCircuitBreakerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/webhook.proto",
}
