// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/webhook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointRequest) Reset() {
	*x = GetEndpointRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointRequest) ProtoMessage() {}

func (x *GetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *GetEndpointRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type GetEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	EventTypes    []string               `protobuf:"bytes,6,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointResponse) Reset() {
	*x = GetEndpointResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointResponse) ProtoMessage() {}

func (x *GetEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *GetEndpointResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEndpointResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEndpointResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetEndpointResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetEndpointResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetEndpointResponse) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type GetCircuitBreakerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCircuitBreakerStateRequest) Reset() {
	*x = GetCircuitBreakerStateRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCircuitBreakerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCircuitBreakerStateRequest) ProtoMessage() {}

func (x *GetCircuitBreakerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCircuitBreakerStateRequest.ProtoReflect.Descriptor instead.
func (*GetCircuitBreakerStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *GetCircuitBreakerStateRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type GetCircuitBreakerStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCircuitBreakerStateResponse) Reset() {
	*x = GetCircuitBreakerStateResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCircuitBreakerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCircuitBreakerStateResponse) ProtoMessage() {}

func (x *GetCircuitBreakerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCircuitBreakerStateResponse.ProtoReflect.Descriptor instead.
func (*GetCircuitBreakerStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *GetCircuitBreakerStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_api_proto_webhook_proto protoreflect.FileDescriptor

const file_api_proto_webhook_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/webhook.proto\x12\n" +
	"webhook.v1\"5\n" +
	"\x12GetEndpointRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"\xa5\x01\n" +
	"\x13GetEndpointResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1f\n" +
	"\vevent_types\x18\x06 \x03(\tR\n" +
	"eventTypes\"@\n" +
	"\x1dGetCircuitBreakerStateRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"6\n" +
	"\x1eGetCircuitBreakerStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2\xd2\x01\n" +
	"\x0fWebhookInternal\x12N\n" +
	"\vGetEndpoint\x12\x1e.webhook.v1.GetEndpointRequest\x1a\x1f.webhook.v1.GetEndpointResponse\x12o\n" +
	"\x16GetCircuitBreakerState\x12).webhook.v1.GetCircuitBreakerStateRequest\x1a*.webhook.v1.GetCircuitBreakerStateResponseB.Z,github.com/webhook-platform/internal/grpc/pbb\x06proto3"

var (
	file_api_proto_webhook_proto_rawDescOnce sync.Once
	file_api_proto_webhook_proto_rawDescData []byte
)

func file_api_proto_webhook_proto_rawDescGZIP() []byte {
	file_api_proto_webhook_proto_rawDescOnce.Do(func() {
		file_api_proto_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)))
	})
	return file_api_proto_webhook_proto_rawDescData
}

var file_api_proto_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_webhook_proto_goTypes = []any{
	(*GetEndpointRequest)(nil),             // 0: webhook.v1.GetEndpointRequest
	(*GetEndpointResponse)(nil),            // 1: webhook.v1.GetEndpointResponse
	(*GetCircuitBreakerStateRequest)(nil),  // 2: webhook.v1.GetCircuitBreakerStateRequest
	(*GetCircuitBreakerStateResponse)(nil), // 3: webhook.v1.GetCircuitBreakerStateResponse
}
var file_api_proto_webhook_proto_depIdxs = []int32{
	0, // 0: webhook.v1.WebhookInternal.GetEndpoint:input_type -> webhook.v1.GetEndpointRequest
	2, // 1: webhook.v1.WebhookInternal.GetCircuitBreakerState:input_type -> webhook.v1.GetCircuitBreakerStateRequest
	1, // 2: webhook.v1.WebhookInternal.GetEndpoint:output_type -> webhook.v1.GetEndpointResponse
	3, // 3: webhook.v1.WebhookInternal.GetCircuitBreakerState:output_type -> webhook.v1.GetCircuitBreakerStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_webhook_proto_init() }
func file_api_proto_webhook_proto_init() {
	if File_api_proto_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_webhook_proto_goTypes,
		DependencyIndexes: file_api_proto_webhook_proto_depIdxs,
		MessageInfos:      file_api_proto_webhook_proto_msgTypes,
	}.Build()
	File_api_proto_webhook_proto = out.File
	file_api_proto_webhook_proto_goTypes = nil
	file_api_proto_webhook_proto_depIdxs = nil
}
