apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-platform.fullname" . }}-config
  labels:
    {{- include "webhook-platform.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}