apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
    {{- include "webhook-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.dispatcher }}
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: "{{ .Values.image.repository }}/dispatcher:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "webhook-platform.fullname" . }}-config
          env:
            - name: SERVICE_NAME
              value: "webhook-dispatcher"
          resources:
            {{- toYaml .Values.resources.dispatcher | nindent 12 }}