apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
    {{- include "webhook-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.scheduler }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}/scheduler:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "webhook-platform.fullname" . }}-config
          env:
            - name: SERVICE_NAME
              value: "webhook-scheduler"
          resources:
            {{- toYaml .Values.resources.scheduler | nindent 12 }}